base_url: http://shop2.qatl.ru/shop/
login_page: http://shop2.qatl.ru/shop/user/login
product_page: http://shop2.qatl.ru/shop/product/casio-mrp-700-1avef
login: lur1x
password: "123456789"
color: Black
order_success_message: "Спасибо за Ваш заказ. В ближайшее время с Вами свяжется менеджер для согласования заказа"
